# Generated by Django 5.0 on 2025-01-27 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandir', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='content_id',
        ),
    ]
