# Generated by Django 5.0 on 2025-01-27 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandir', '0002_remove_event_content_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='images',
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/images/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mandir.event')),
            ],
        ),
    ]
