# Generated by Django 5.0 on 2025-02-10 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandir', '0003_remove_event_images_eventimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='content_id',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='content_id',
        ),
    ]
